version: '3'
services:
  app:
    build: .
    environment:
      NODE_ENV: production
      PORT: 80
      DOMAIN: myawesomeapp.domain.example
      EMAIL: info@awesomeapp.example
    ports:
      - "80:8080"
      - "433:8080"
    container_name: hackaton_web_app
