version: '3.9'
services:
  app:
    build: .
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - "3000:8080"
    container_name: hackaton-web-app
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules

volumes:
  app: null
